### ISSUE TITLE
Deletes Beat Saber and disconnects

### ISSUE THREAD

**Issue by Jajoo2** [Lauriethefish/ModsBeforeFriday#10]
That's all it does. This website is a scam!

**Comment by XoToM** [comment]
That is definitely not what mbf is supposed to do. Could you give us a bit more info on what happened so we can try to fix this? 

- How far into the process were you when mbf disconnected? 
- Did mbf show any errors when it happened?
- Have you tried mbf again, and if so has this happened again?
- Which quest did you use mbf on? 
- Which web browser do you use?
- Which version of beat saber did you have before it got deleted?

**Comment by Tomaseeek-rozryty** [comment]
Hello there, i have same issue.

**Comment by Lauriethefish** [comment]
Closing due to lack of comment
