### ISSUE TITLE
Meta quest support

### ISSUE THREAD

**Issue by dragon123456789** [Lauriethefish/ModsBeforeFriday#11]
The latest ver of beat saber is 1.29 on meta and it seems  it cant be modded. Any suggestions?? its been a few days now without success

**Comment by Lauriethefish** [comment]
ModsBeforeFriday is unfortunately only designed for modding versions 1.35 or newer, which means it cannot support Quest 1, as this only has Beat Saber version 1.29.
Modding older versions requires a different modloader which would need to have support added, which is a lot of work for me when Quest 1 was never a goal of this project.

Therefore I am closing this as not planned.
