### ISSUE TITLE
Pre v51 detection.

### ISSUE THREAD

**Issue by AltyFox** [Lauriethefish/ModsBeforeFriday#12]
On non-Q1 headsets, If the headset happens to be pre v51, The copy of the game downloaded becomes the Quest 1 copy. Mbf currently spits out an error, and even mentions possible piracy. 
Add a secondary detection for Android 10 on newer headsets and inform the user. They need to update their headset and reinstall the game.

**Comment by Lauriethefish** [comment]
Fixed in a386c04a3c294766576174a46c814b4355bb0a58
