### ISSUE TITLE
No Internet Error

### ISSUE THREAD

**Issue by Konack** [Lauriethefish/ModsBeforeFriday#14]
I am able to successfully connect my quest 2 but when I get to the "Fetching core mod index" it sits on it for a couple minutes and then fails with the error 

> No internet
> It seems as though your Quest has no internet connection.
> 
> To mod Beat Saber, MBF needs to download files such as a mod loader and several essential mods.
> This occurs on your Quest's connection. Please make sure that WiFi is enabled, then refresh the page.

I have tried on 2 different windows computers and even connected my quest to my phone's hotspot to rule out any filtering on my network but I get the same result every time.

My quest 2 is on version 65 and my chrome version is 125,

**Comment by Konack** [comment]
service was down.

**Comment by Eks2** [comment]
@Konack how did you check whether the service was up or down? I'm getting this same issue now and I'm wondering if it's for the same reason

**Comment by Konack** [comment]
Yup, that's where I found out.
