### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by Utfkytcvutugyu** [Lauriethefish/ModsBeforeFriday#17]
So i was connecting my vr to my phone and the website said no internet so I checked my vr and my phone the phone and the vr said I have internet  so I tried again and it still said no internet

**Comment by iNeoTroniC** [comment]
Same here... PC and Quest do have internet, Quest is on v65 and connected via Wifi (browsing works):

Preparing agent: used to communicate with your Quest.
Agent is up to date
Loading installed mods
Searching for Beat Saber app
Fetching core mod index

==> No internet
It seems as though your Quest has no internet connection.

To mod Beat Saber, MBF needs to download files such as a mod loader and several essential mods.
This occurs on your Quest's connection. Please make sure that WiFi is enabled, then refresh the page.

**Comment by soErnsthaft** [comment]
Can confirm issue.
PC using Chrome (v125.0.6422.142 64bit) on Windows 11 with Quest 3 (v65.0.0546.341.596219110).

Procedure seems to start normaly but gets stuck on "Fetching core mod index" for a while (3 - 5 seconds).
![grafik](https://github.com/Lauriethefish/ModsBeforeFriday/assets/172433970/c058a4b7-816d-4435-af01-c1ed80b986ff)

Then the "No internet" screen appears, although Quest is connected to wifi and browsing works.
![grafik](https://github.com/Lauriethefish/ModsBeforeFriday/assets/172433970/0bdb8084-97d2-4f6c-aae4-b1ac634a3409)

**Comment by Utfkytcvutugyu** [comment]
That’s the problem I’m having

**Comment by Dixip52** [comment]
same here

**Comment by Hen105** [comment]
Same here...

**Comment by Lauriethefish** [comment]
This issue is due to the BMBF gitlab which is currently down, preventing MBF from checking if core mods are installed.
It should be fixed within the day.

**Comment by Utfkytcvutugyu** [comment]
Thank you

**Comment by soErnsthaft** [comment]
> This issue is due to the BMBF gitlab which is currently down, preventing MBF from checking if core mods are installed. It should be fixed within the day.

Thank you for the fast response.
Glad its nothing major.
