### ISSUE TITLE
MBF is Outdated

### ISSUE THREAD

**Issue by Windows98SE-dev** [Lauriethefish/ModsBeforeFriday#20]
Hello, the developper of Mapping Extension gave me a testing build of the mod and when I upload it to MBF it says "Failed to import file: Error: `Failed to parse manifest Caused by: QMOD specified schema version 1.2.0 which was newer than the maximum supported version 1.1.0. Is MBF out of date, or did the mod developer make a mistake?" 
Note : The Testing Build Is For Beat Saber 1.37

**Comment by Lauriethefish** [comment]
This issue is now fixed, please wait up to 5 minutes for the changes to be reflected in your browser.
