### ISSUE TITLE
Crashing on v67

### ISSUE THREAD

**Issue by mexanick67** [Lauriethefish/ModsBeforeFriday#22]
After installing mbf on 1.37 version of game and v67 firmware it just shows Beat Saber logo and then crash

**Comment by Lauriethefish** [comment]
Can you please provide a log file using the option in the MBF settings tab?

**Comment by mexanick67** [comment]
Don't now what happend but 1 hour ago. It crashed. Now It's running normal. Here's log anyway.
[logcat.log](https://github.com/user-attachments/files/16118754/logcat.log)

**Comment by Lauriethefish** [comment]
yep, all seems normal in that log now.
Not sure what could be the issue.

**Comment by mexanick67** [comment]
Ok. If crash happend again, i will try to catch it's log and uploda it here
