### ISSUE TITLE
Device not found in connection list

### ISSUE THREAD

**Issue by KMANCOOL17** [Lauriethefish/ModsBeforeFriday#23]
When I click "Connect to Quest", The meta quest 3 device does not show up.

**Comment by Lauriethefish** [comment]
The "available devices" window that you're seeing is actually part of your browser, not MBF, so to be clear, this cannot be considered an "issue" with MBF, so I'm closing it.

But I can help you out with the problem at hand:
- You need to make sure you've enabled developer mode on your Quest 3, even if you think you have it enabled, double check in the meta app please.
- If it's still not connecting, then try a different USB cable.
- Make sure your browser is up to date.
- Try a different browser if necessary.

**Comment by echostorm983** [comment]
I followed all steps, Quest 2 device never shows up. Dev mode was on too, I also double checked and followed the official guide for USB debugging.

**Comment by echostorm983** [comment]
Nevermind it was my cable lol.
