### ISSUE TITLE
Feature Request: Select multiple mods for batch install

### ISSUE THREAD

**Issue by PaulMndn** [Lauriethefish/ModsBeforeFriday#24]
Quality of life feature request:

I'd like to be able to select all mods I want to install; and then, install them all in one go by pressing an "install selected"-button. 

Currently, I have to wait for each mod to install individually before browsing for additional mods.

**Comment by Lauriethefish** [comment]
Linked the wrong issue in 52558954a35f0f5946ad4b503e0757d2f34c301d but this feature has now been implemented on the `main` branch, I need to do some testing on mobile before I will release it.

**Comment by Lauriethefish** [comment]
Now implemented

**Comment by PaulMndn** [comment]
Looks good, thanks. One note I have is, that the flag icon to select multiple mods looks just like the one commonly used to flag and report stuff. 
It might be clearer to the user if it's something like the typical select checkbox/circle:
![image](https://github.com/user-attachments/assets/239bcfba-5ced-483b-abf2-71c1c74bbb0f)
([link outline](https://fonts.google.com/icons?icon.category=UI+actions&selected=Material+Symbols+Outlined:check_box_outline_blank:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=select&icon.size=24&icon.color=%235f6368&icon.style=Outlined) and [selected](https://fonts.google.com/icons?icon.category=UI+actions&selected=Material+Symbols+Outlined:check_box:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=select&icon.size=24&icon.color=%235f6368&icon.style=Outlined)) or possibly a circular variation or something?

**Comment by Lauriethefish** [comment]
@PaulMndn This icon has now been improved, here's an image:
![image](https://github.com/user-attachments/assets/f3480320-404b-49b5-9cca-343a82817464)

**Comment by PaulMndn** [comment]
Looks good, I like it :)
