### ISSUE TITLE
Easter egg for people trying to install pc mods

### ISSUE THREAD

**Issue by FrozenAlex** [Lauriethefish/ModsBeforeFriday#27]
It'd be nice to add a special message when people try to install .dll files on quest. Something informative and funny

**Comment by Lauriethefish** [comment]
Added special message in 54a8aac7204841e364fbedc53d525ec9a1ba374f
IMO there's no need to make it funny, it just explains that PC mods can't be installed on Quest.
![example of new message](https://github.com/user-attachments/assets/b4476d42-c48f-4bcd-8439-77eec0da8087)
