### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by Divide-By-0** [Lauriethefish/ModsBeforeFriday#28]
I'd like to donate on via Github sponsors or anything else to this useful tool. Is there any payment info provided for the dev?

**Comment by Lauriethefish** [comment]
Unfortunately right now I'm not taking donations, but this might change in the near future.

**Comment by Lauriethefish** [comment]
I have applied for github sponsors, but they seem to be behind on reviewing applications, so it might be a little bit!

**Comment by Lauriethefish** [comment]
Hello, the application has gone through. You may now donate [here](https://github.com/sponsors/Lauriethefish)
Thank you very much!
