### ISSUE TITLE
Older Version Error 

### ISSUE THREAD

**Issue by F4tal3rr0r** [Lauriethefish/ModsBeforeFriday#29]
When I try to download an older version of modded beatsaber I get these errors 

An error occured while patching Error: `Failed to patch game

Caused by:

0: Failed to downgrade and patch APK

1: Failed to download diffs

2: Failed to download diff file

3: Failed to download file after maximum attempts

4: Failed to request file

5: https://github.com/Lauriethefish/mbf-diffs/releases/download/1.0.0/bs-obb-1.37.2_10091729318-to-1.35.0_8016709773.obb.diff: status code 404`

**Comment by Lauriethefish** [comment]
Now fixed.
