### ISSUE TITLE
queue system 

### ISSUE THREAD

**Issue by Majed0X** [Lauriethefish/ModsBeforeFriday#31]
is it possible to add queue system when you downloading mods so i can add punch of mods than hit start and just leave its useful for people that have a bad internet and its kinda annoying unkess if mods would break if u install them at once ?

**Comment by Lauriethefish** [comment]
This is essentially the same issue as #24 so I'm closing as a duplicate

**Comment by Majed0X** [comment]
oh lmao sorry for the bother
