### ISSUE TITLE
How can you tell wich BS version is supported and which mods are compatible without plugging the headset ?

### ISSUE THREAD

**Issue by megosugit** [Lauriethefish/ModsBeforeFriday#33]
Hi,

Before updating my BS version, I wanted to check which build was supported by MBF and which mods were available for this build, but I can't find it anywhere.

Is there a way without plugging the headset ?

**Comment by Lauriethefish** [comment]
> How can you tell wich BS version
MBF always downgrades to the latest moddable version - you don't need to obtain the latest supported version separately.

However, to check which version this is, head [here](https://mods.bsquest.xyz/).
The dropdown at the top of the page shows the latest moddable version, select this version then scroll around to check the available mods.

**Comment by megosugit** [comment]
great link, thanks !

so it seems 1.37.0 is the latest supported moddable version at the moment. I guess it is up to the modders and not you.

Thanks !

**Comment by Lauriethefish** [comment]
yeah MBF is a mod installer, I don't control the releases of mods.
Once mods release, they automatically show up on mbf
