### ISSUE TITLE
Feature request: Update all installed mods

### ISSUE THREAD

**Issue by PaulMndn** [Lauriethefish/ModsBeforeFriday#34]
A button to update all installed mods for which a new version is available (including core mods). 

Also, the log tells me that some core mods are outdated, but core mods are not listed in the mod list. How can I update those? Do I have to use "Reinstall only core mods"?

**Comment by Lauriethefish** [comment]
> A button to update all installed mods for which a new version is available
This is a good idea, not sure where I'd put the button but I'll work it out at some point

> Also, the log tells me that some core mods are outdated, but core mods are not listed in the mod list. 
If core mods are outdated, MBF gives you a prompt like this:
![image](https://github.com/user-attachments/assets/db87eec7-2c8b-4de8-84a6-daa620b7d42a)
to urgently suggest you update them.

I could add a slightly less intrusive prompt in this menu to update non-core mods.

**Comment by Lauriethefish** [comment]
In ea023ea74f354e8cbc4382d75ffd52763824b8ad, the "batch install" system for mods will now automatically include any outdated mods in the install by default (although you can manually remove them).

This should satisfy the requirement of having a button to update all mods.

**Comment by Lauriethefish** [comment]
@PaulMndn I suppose if you want to check if out and give feedback before I push it to the main site
[nightly site](https://lauriethefish.github.io/mbf-nightly/)

**Comment by Lauriethefish** [comment]
Feature now deployed to the main site
