### ISSUE TITLE
Modding for 1.35 Disabled?

### ISSUE THREAD

**Issue by Pearpear43** [Lauriethefish/ModsBeforeFriday#37]
Hello, I modded version 1.35 on my oculus 2 using MBF a couple of months ago and everything worked fine. I then realized that the Replay Mod was created for 1.37 recently so I updated. I started playing and noticed a delay, one that a didn't have in 1.35. It was small but noticeable, and enough to throw me off. I went to mod my quest again today as I was told that I can still mod for 1.35, but that setting does not seem to appear anymore. Is there any reason for this, and is there any chance for it to return?

**Comment by Lauriethefish** [comment]
> Is there any reason for this
The option to mod 1.35 is disabled as all mods that were available for version 1.35 are now available for 1.37, so there's no need to use the older version.

Having the option for 1.35 requires an extra diff/delta file to be generated whenever a new BS version comes out that takes the user to 1.35. Generating deltas, particularly for such a large version difference, takes a long time, and I won't do it unless there's a clear point.

> I started playing and noticed a delay
This can be fixed using the audio offset in the base game player settings. The audio offset changes the timing of the music in relation to the notes, so you can use it to fix the "delay" issue.

> and is there any chance for it to return?
No. As well as it requiring extra effort from me, having the option available to downgrade encourages users to do it, when there is currently no real application. I want to encourage users to keep to the latest moddable version whenever possible.
