### ISSUE TITLE
Crash On V69

### ISSUE THREAD

**Issue by Zackmandude1** [Lauriethefish/ModsBeforeFriday#38]
every time i open beat saber, it gets to the health and safety warnings, but it crashes after about 30 seconds of the app being open

**Comment by Lauriethefish** [comment]
Do you have any additional mods other than the core mods installed?

**Comment by Zackmandude1** [comment]
no

**Comment by Lauriethefish** [comment]
Can you please use the "ADB Log" feature in the tools tab to get a log?

**Comment by Zackmandude1** [comment]
[logcat.log](https://github.com/user-attachments/files/17066181/logcat.log)
