### ISSUE TITLE
Add manifest workaround for MRC (mixed reality capture)

### ISSUE THREAD

**Issue by ElDavoo** [Lauriethefish/ModsBeforeFriday#4]
Hello,
as I wrote [here](https://github.com/Lauriethefish/QuestPatcher/issues/174), I'd be nice if MBF also patches the manifest to enable MRC.

**Comment by Lauriethefish** [comment]
This is possible but will require a bit of backend work, since right now MBF doesn't touch much inside the application element. (or at least, it doesn't have a way to do so while allowing the changes to be reversible).
It will be implemented soonish.

**Comment by Lauriethefish** [comment]
Successfully implemented the workaround in 43a4ee6d6f9c9175356e2bfbb444f5a0ad5c07fb but it causes the APK to fail to install if hand tracking is also enabled. Strangely, if ALL options are enabled including MRC workaround and hand tracking, then the APK installs fine.

This is presumably a bug in the axml library.

**Comment by Lauriethefish** [comment]
The source of the bug has been determined so MRC workaround is now merging with main, I'll then deploy and close the issue.

**Comment by Lauriethefish** [comment]
Feature is deployed.
