### ISSUE TITLE
Installs Mods only on one Quest User

### ISSUE THREAD

**Issue by OliDMX** [Lauriethefish/ModsBeforeFriday#43]
So i just discovered, that after a reinstall of MBF that it just installs the modded version onto the first profile (device owner) and does not modify other beat saber instances in a different user profile. Also tried logging into the other profile and letting MBF check if its modded and it says it is modded, but it just starts vanilla. 
maybe a solution would be, telling MBF where to look for mods or define which profile should be modded.
love your app btw, thanks!

**Comment by OliDMX** [comment]
just did a full factory reset of a quest 2 and installed beat saber only in the second user. MBF does not detect any beat saber.. sadge

**Comment by Lauriethefish** [comment]
Unfortunately, it's not possible for MBF to access the files of other users via USB, so it can't actually mod them (it can't put the mod files in the required places). Therefore, right now this is one I can't implement.
