### ISSUE TITLE
Mbf still says I’m on 1.29

### ISSUE THREAD

**Issue by ThomasRagingBoner** [Lauriethefish/ModsBeforeFriday#45]
So when I was setting it up it said I was on version 1.29 of beat saber and so I deleted the game and reinstalled it, even after it still says I’m on 1.29 and I even tried switching versions with quest app switcher and mbf is still giving me the same prompt

**Comment by Lauriethefish** [comment]
This is due to your game being set to a legacy branch, and is not an issue with MBF.
Please join the [BSMG discord server](https://discord.com/invite/beatsabermods) and go to `#quest-help` for further support.
