### ISSUE TITLE
Importing playlists

### ISSUE THREAD

**Issue by dacadla** [Lauriethefish/ModsBeforeFriday#6]
It seems like MBF does not recognize .bplist files. It would be a great feature to have.

**Comment by Lauriethefish** [comment]
Should be fairly easy to add although I am very busy at the moment so won't be able to get to it for a while.
Anybody that feels like contributing, it should be fairly easy to add it [here](https://github.com/Lauriethefish/ModsBeforeFriday/blob/main/mbf-agent/src/handlers.rs#L198)

**Comment by dacadla** [comment]
might learn rust and actually add this myself, no promises

**Comment by dacadla** [comment]
yeah no, i'm too lazy to learn rust, sorry. i'll just stick to scala and hope someone adds this

**Comment by yungcomputerchair** [comment]
I can look into this ^-^

**Comment by Lauriethefish** [comment]
Anybody still looking into this @yungcomputerchair?

**Comment by szarroug3** [comment]
looks like this is all that's needed according to jonas: https://github.com/Metalit/PlaylistCore/pull/8

**Comment by Lauriethefish** [comment]
This PlaylistCore issue is now completed, and therefore MBF will copy playlists to the required folder.

Hence this issue is completed.
